'use strict';
window.mountPresetLibrary=(root,{onAdd,compact=false}={})=>{
  const S=Studio,E=S.element;let scope='all',folderFilter=null;root.replaceChildren();
  const top=E('div',undefined,'library-actions'),newFolder=E('button','+ New folder','ui-button'),newPreset=E('button','+ New Template','ui-button primary');top.append(newFolder,newPreset);
  const search=E('input');search.type='search';search.placeholder='Search templates...';search.className='library-search';
  const tabs=E('div',undefined,'segmented');for(const [id,label]of [['all','Все'],['common','Общие'],['mine','Мои']]){const b=E('button',label);b.dataset.scope=id;b.setAttribute('aria-pressed',String(id===scope));b.onclick=()=>{scope=id;folderFilter=null;render();};tabs.append(b);}root.append(top,search,tabs,E('div',undefined,'folder-tree'));const tree=root.querySelector('.folder-tree');if(compact){const a=E('a','Открыть библиотеку','library-route');a.href='presets.html';root.append(a);}search.oninput=render;
  function modal(title,content){const d=E('dialog',undefined,'studio-dialog');const h=E('header');h.append(E('h2',title));const x=E('button','×','icon-button');x.onclick=()=>d.close();h.append(x);d.append(h,content);document.body.append(d);d.onclose=()=>d.remove();d.onclick=e=>{if(e.target===d)d.close();};d.showModal();return d;}
  const field=(label,input)=>{const l=E('label',label);l.append(input);return l;};
  function visibility(value='mine'){const s=E('select');s.add(new Option('Мой шаблон','mine'));if(S.isAdmin())s.add(new Option('Общий для всех','common'));s.value=value;return s;}
  function presetEditor(p=null){const form=E('form',undefined,'stack'),name=E('input'),text=E('textarea'),folder=E('select'),access=visibility(p?.scope);name.required=true;name.maxLength=80;name.value=p?.name||'';text.required=true;text.rows=7;text.value=p?.text||'';for(const f of S.listFolders())folder.add(new Option(f.name+(f.scope==='mine'?' · моя':''),f.id));if(p)folder.value=p.folder;else if(folderFilter)folder.value=folderFilter;const error=E('p','','form-error'),save=E('button','Сохранить','ui-button primary');save.type='submit';form.append(field('Название',name),field('Текст шаблона',text),field('Папка',folder),field('Доступ',access),error,save);const d=modal(p?'Редактировать шаблон':'Новый шаблон',form);form.onsubmit=async e=>{e.preventDefault();save.disabled=true;error.textContent='';try{await S.savePreset({id:p?.id,name:name.value,text:text.value,folder:folder.value,scope:access.value});d.close();render();S.notify('Шаблон сохранён');}catch(err){error.textContent=err.message;}finally{save.disabled=false;}};}
  function folderEditor(f=null){const form=E('form',undefined,'stack'),name=E('input'),access=visibility(f?.scope);name.required=true;name.maxLength=60;name.value=f?.name||'';const error=E('p','','form-error'),save=E('button','Сохранить папку','ui-button primary');save.type='submit';form.append(field('Название',name),field('Доступ',access),error,save);const d=modal(f?'Редактировать папку':'New folder',form);form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{await S.saveFolder({id:f?.id,name:name.value,scope:access.value});d.close();render();}catch(err){error.textContent=err.message;}finally{save.disabled=false;}};}
  function confirmDelete(title,action){const box=E('div',undefined,'stack');box.append(E('p','Удаление не изменит уже добавленные в Canvas ноды.'));const b=E('button','Удалить','ui-button danger'),d=modal(title,box);box.append(b);b.onclick=async()=>{b.disabled=true;try{await action();d.close();render();}catch(err){S.notify(err.message,'error');}finally{b.disabled=false;}};}
  function render(){tree.replaceChildren();for(const b of tabs.children)b.setAttribute('aria-pressed',String(b.dataset.scope===scope));const q=search.value.trim().toLowerCase(),items=S.listPresets().filter(p=>(scope==='all'||p.scope===scope)&&(`${p.name} ${p.text}`).toLowerCase().includes(q));for(const f of S.listFolders()){const content=items.filter(p=>p.folder===f.id);if(scope==='common'&&f.scope!=='common')continue;if(q&&!content.length)continue;const group=E('section',undefined,'template-folder');const head=E('div',undefined,'template-folder-head');head.append(E('div',f.name),E('small',String(content.length)));const actions=E('div',undefined,'folder-actions');const add=E('button','+ Template');add.onclick=()=>{folderFilter=f.id;presetEditor();};actions.append(add);if(S.canEdit(f)&&!f.builtin){const edit=E('button','Rename');edit.onclick=()=>folderEditor(f);const del=E('button','Delete');del.onclick=()=>confirmDelete('Удалить папку?',()=>S.deleteFolder(f.id));actions.append(edit,del);}head.append(actions);group.append(head);const grid=E('div',undefined,'template-grid');if(!content.length)grid.append(E('div','Папка пуста','empty-card'));for(const p of content){const card=E('article',undefined,'template-card');card.append(E('small',p.scope==='common'?'COMMON':'PRIVATE'),E('h3',p.name),E('p',p.text));const a=E('div',undefined,'template-card-actions');const use=E(onAdd?'button':'a','+ На Canvas','ui-button');if(onAdd)use.onclick=()=>onAdd(p);else use.href='spaces.html';a.append(use);if(S.canEdit(p)){const edit=E('button','Edit');edit.onclick=()=>presetEditor(p);const del=E('button','Delete');del.onclick=()=>confirmDelete('Удалить шаблон?',()=>S.deletePreset(p.id));a.append(edit,del);}card.append(a);grid.append(card);}group.append(grid);tree.append(group);}if(!items.length&&!q){const empty=E('div',undefined,'library-empty');empty.append(E('strong','No templates yet.'),E('span','Создай шаблон с {{variable}} или обычным текстом и добавляй его в Canvas одним кликом.'));tree.append(empty);}if(!items.length&&q)tree.append(E('div','Ничего не найдено','library-empty'));}
  newFolder.onclick=()=>folderEditor();newPreset.onclick=()=>presetEditor();render();return {render};
};
